name: Generate Snake Game

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the Snake Game
        uses: Platane/snk@v3
        with:
          # github_user: Your GitHub username
          github_user: shaimaa-alrajeh
          outputs: dist/snake.svg

      - name: Upload the Snake Game
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
